// lib/medicineDb.ts
// Comprehensive dental & general-practice medicine database
// Used by prescription writer for autocomplete, interaction checking, and smart defaults

export type DrugClass =
  | "Antibiotic"
  | "Analgesic"
  | "NSAID"
  | "Antifungal"
  | "Antiseptic"
  | "Corticosteroid"
  | "Antihistamine"
  | "Anxiolytic"
  | "Antacid"
  | "Proton Pump Inhibitor"
  | "Antiemetic"
  | "Vitamin & Supplement"
  | "Mouthwash & Topical"
  | "Local Anesthetic"
  | "Muscle Relaxant"
  | "Antiviral"
  | "Decongestant"
  | "Fluoride"
  | "Haemostatic"
  | "Bone Resorption Inhibitor"

export type Frequency =
  | "Once daily (OD)"
  | "Twice daily (BD)"
  | "Three times daily (TDS)"
  | "Four times daily (QID)"
  | "Every 6 hours (Q6H)"
  | "Every 8 hours (Q8H)"
  | "Every 12 hours (Q12H)"
  | "Every 4-6 hours (PRN)"
  | "At bedtime (HS)"
  | "As needed (SOS)"
  | "Once weekly"
  | "Stat (single dose)"

export interface Medicine {
  id: string
  genericName: string
  brandNames: string[]
  drugClass: DrugClass
  category: string // subgroup label for display
  strengths: string[]       // e.g. ["250mg", "500mg"]
  defaultStrength: string
  defaultFrequency: Frequency
  defaultDuration: string   // e.g. "5 days", "7 days"
  defaultDose: string       // e.g. "1 tablet"
  route: string             // "Oral" | "Topical" | "IV" | "Sublingual" etc.
  foodInstruction: string   // "After meals" | "Before meals" | "With food" | "Empty stomach"
  contraindications: string[]
  interactions: string[]    // generic names it interacts with
  sideEffects: string[]
  notes: string
  tags: string[]            // searchable keywords
}

const MEDICINES: Medicine[] = [
  // ─── ANTIBIOTICS ──────────────────────────────────────────────────────────

  {
    id: "amoxicillin",
    genericName: "Amoxicillin",
    brandNames: ["Amoxil", "Mox", "Novamox", "Trimox"],
    drugClass: "Antibiotic",
    category: "Penicillin",
    strengths: ["250mg", "500mg", "875mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "5 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Penicillin allergy", "Mononucleosis"],
    interactions: ["Warfarin", "Methotrexate", "Oral contraceptives"],
    sideEffects: ["Diarrhoea", "Nausea", "Rash", "Allergic reaction"],
    notes: "First-line antibiotic for dental infections, periapical abscess, and periodontal infections.",
    tags: ["dental infection", "abscess", "penicillin", "broad spectrum"],
  },
  {
    id: "amoxicillin-clavulanate",
    genericName: "Amoxicillin + Clavulanate",
    brandNames: ["Augmentin", "Clavam", "Co-Amoxiclav", "Moxclav"],
    drugClass: "Antibiotic",
    category: "Penicillin + Beta-lactamase inhibitor",
    strengths: ["375mg", "625mg", "1000mg"],
    defaultStrength: "625mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "7 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Penicillin allergy", "Hepatic dysfunction", "Jaundice"],
    interactions: ["Warfarin", "Methotrexate", "Allopurinol"],
    sideEffects: ["Diarrhoea", "Nausea", "Vomiting", "Hepatotoxicity (rare)"],
    notes: "For moderate-severe dental infections or beta-lactamase producing organisms. Take with the first bite of a meal.",
    tags: ["dental abscess", "oral infection", "augmentin", "severe infection"],
  },
  {
    id: "metronidazole",
    genericName: "Metronidazole",
    brandNames: ["Flagyl", "Metrogyl", "Elyzol", "Metronid"],
    drugClass: "Antibiotic",
    category: "Nitroimidazole",
    strengths: ["200mg", "400mg", "500mg"],
    defaultStrength: "400mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["First trimester pregnancy", "Alcohol use", "Disulfiram use"],
    interactions: ["Alcohol", "Warfarin", "Lithium", "Disulfiram"],
    sideEffects: ["Metallic taste", "Nausea", "Headache", "Peripheral neuropathy (prolonged use)"],
    notes: "Excellent anaerobic coverage — often combined with Amoxicillin for dental infections and ANUG (acute necrotising ulcerative gingivitis). Strict alcohol avoidance required.",
    tags: ["anaerobic", "ANUG", "gingivitis", "periodontal", "abscess", "flagyl"],
  },
  {
    id: "clindamycin",
    genericName: "Clindamycin",
    brandNames: ["Dalacin C", "Clindac", "Cleocin", "Clincin"],
    drugClass: "Antibiotic",
    category: "Lincosamide",
    strengths: ["150mg", "300mg"],
    defaultStrength: "300mg",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "7 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Clindamycin hypersensitivity", "History of C. diff colitis"],
    interactions: ["Neuromuscular blocking agents", "Erythromycin"],
    sideEffects: ["Diarrhoea", "C. difficile colitis", "Nausea", "Oesophageal ulceration"],
    notes: "Alternative for penicillin-allergic patients. Good bone penetration — preferred for osteomyelitis. Take with a full glass of water. Infective endocarditis prophylaxis: single 600mg dose.",
    tags: ["penicillin allergy", "osteomyelitis", "endocarditis prophylaxis", "bone infection"],
  },
  {
    id: "azithromycin",
    genericName: "Azithromycin",
    brandNames: ["Zithromax", "Azee", "Azithral", "Z-pack"],
    drugClass: "Antibiotic",
    category: "Macrolide",
    strengths: ["250mg", "500mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "3 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "Before meals",
    contraindications: ["Macrolide allergy", "QT prolongation", "Hepatic disease"],
    interactions: ["Warfarin", "Digoxin", "Antacids (aluminium/magnesium)", "QT-prolonging drugs"],
    sideEffects: ["Nausea", "Diarrhoea", "Abdominal pain", "QT prolongation (rare)"],
    notes: "Short 3-day course. Alternative for penicillin-allergic patients. Useful for periodontitis adjunct therapy.",
    tags: ["macrolide", "short course", "penicillin allergy", "periodontitis"],
  },
  {
    id: "doxycycline",
    genericName: "Doxycycline",
    brandNames: ["Vibramycin", "Doxin", "Doxt-SL", "Doxylin"],
    drugClass: "Antibiotic",
    category: "Tetracycline",
    strengths: ["50mg", "100mg"],
    defaultStrength: "100mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "7 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Pregnancy", "Children under 8 years", "Severe hepatic disease"],
    interactions: ["Antacids", "Iron supplements", "Dairy products", "Warfarin", "Oral contraceptives"],
    sideEffects: ["Photosensitivity", "GI upset", "Oesophageal irritation", "Tooth staining (children)"],
    notes: "Sub-antimicrobial dose (20mg BD) used for chronic periodontitis. Avoid lying down 30 mins after. Sun protection required. Space 2h apart from antacids/dairy.",
    tags: ["periodontitis", "tetracycline", "chronic periodontitis", "sub-antimicrobial"],
  },
  {
    id: "ciprofloxacin",
    genericName: "Ciprofloxacin",
    brandNames: ["Cipro", "Ciplox", "Cifran", "Ciprolet"],
    drugClass: "Antibiotic",
    category: "Fluoroquinolone",
    strengths: ["250mg", "500mg", "750mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "7 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Fluoroquinolone allergy", "Tendinopathy history", "Children (avoid)", "Pregnancy"],
    interactions: ["Antacids", "Dairy", "Warfarin", "Theophylline", "NSAIDs"],
    sideEffects: ["Tendon rupture", "GI upset", "QT prolongation", "Photosensitivity", "CNS effects"],
    notes: "Reserve for severe infections or cases not responding to first-line. Risk of tendonitis/rupture, especially with steroids or elderly patients.",
    tags: ["fluoroquinolone", "severe infection", "broad spectrum"],
  },
  {
    id: "cephalexin",
    genericName: "Cephalexin",
    brandNames: ["Keflex", "Ciplox-TZ", "Sporidex", "Cephoral"],
    drugClass: "Antibiotic",
    category: "First-generation Cephalosporin",
    strengths: ["250mg", "500mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "7 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Cephalosporin allergy", "Severe penicillin allergy (10% cross-reaction)"],
    interactions: ["Warfarin", "Probenecid"],
    sideEffects: ["GI upset", "Allergic reaction", "Diarrhoea"],
    notes: "Alternative to amoxicillin. Good for soft tissue dental infections. Endocarditis prophylaxis: single 2g dose.",
    tags: ["cephalosporin", "soft tissue", "endocarditis prophylaxis"],
  },

  // ─── ANALGESICS ───────────────────────────────────────────────────────────

  {
    id: "paracetamol",
    genericName: "Paracetamol",
    brandNames: ["Crocin", "Dolo", "Tylenol", "Calpol", "Panadol"],
    drugClass: "Analgesic",
    category: "Non-opioid analgesic",
    strengths: ["325mg", "500mg", "650mg", "1000mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "3 days",
    defaultDose: "1-2 tablets",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Severe hepatic impairment", "Chronic alcoholism"],
    interactions: ["Warfarin (high doses)", "Alcohol", "Isoniazid"],
    sideEffects: ["Hepatotoxicity (overdose)", "Rare hypersensitivity"],
    notes: "First-line analgesic for mild-moderate dental pain. Max 4g/day. Safe in pregnancy and paediatrics (weight-based dosing). Preferred over NSAIDs for patients with GI issues.",
    tags: ["pain relief", "fever", "mild pain", "safe", "paediatric"],
  },
  {
    id: "tramadol",
    genericName: "Tramadol",
    brandNames: ["Ultram", "Tramazac", "Contramal", "Ultracet"],
    drugClass: "Analgesic",
    category: "Opioid analgesic",
    strengths: ["50mg", "100mg"],
    defaultStrength: "50mg",
    defaultFrequency: "Every 6 hours (Q6H)",
    defaultDuration: "3 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Epilepsy", "MAO inhibitor use", "Respiratory depression", "Opioid allergy"],
    interactions: ["SSRIs (serotonin syndrome)", "MAOIs", "CNS depressants", "Alcohol"],
    sideEffects: ["Nausea", "Dizziness", "Constipation", "Dependence risk", "Seizures"],
    notes: "For moderate-severe post-operative dental pain. Short-term use only. Schedule H drug — caution with dependence-prone patients.",
    tags: ["severe pain", "post-op", "opioid", "schedule H"],
  },
  {
    id: "tramadol-paracetamol",
    genericName: "Tramadol + Paracetamol",
    brandNames: ["Ultracet", "Tramazac-TH", "Dolocold Plus"],
    drugClass: "Analgesic",
    category: "Combination analgesic",
    strengths: ["37.5mg/325mg"],
    defaultStrength: "37.5mg/325mg",
    defaultFrequency: "Every 6 hours (Q6H)",
    defaultDuration: "3 days",
    defaultDose: "1-2 tablets",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Epilepsy", "MAO inhibitor use", "Severe hepatic impairment"],
    interactions: ["SSRIs", "MAOIs", "CNS depressants", "Warfarin"],
    sideEffects: ["Nausea", "Dizziness", "Constipation"],
    notes: "Combined formulation for moderate post-operative pain. Lower tramadol dose reduces side-effect risk.",
    tags: ["post-op pain", "combination", "moderate pain"],
  },

  // ─── NSAIDs ───────────────────────────────────────────────────────────────

  {
    id: "ibuprofen",
    genericName: "Ibuprofen",
    brandNames: ["Brufen", "Advil", "Nurofen", "Combiflam (with Paracetamol)"],
    drugClass: "NSAID",
    category: "Propionic acid derivative",
    strengths: ["200mg", "400mg", "600mg", "800mg"],
    defaultStrength: "400mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Peptic ulcer", "Renal impairment", "Third trimester pregnancy", "NSAID allergy", "Aspirin-sensitive asthma"],
    interactions: ["Aspirin", "Warfarin", "ACE inhibitors", "Lithium", "Methotrexate"],
    sideEffects: ["GI upset", "Peptic ulcer", "Renal dysfunction", "Fluid retention", "Cardiovascular risk"],
    notes: "Excellent anti-inflammatory for pulpitis and periodontal pain. Always take with food. Consider PPI cover for prolonged use.",
    tags: ["inflammation", "pulpitis", "dental pain", "NSAID", "anti-inflammatory"],
  },
  {
    id: "diclofenac",
    genericName: "Diclofenac Sodium",
    brandNames: ["Voveran", "Volini (topical)", "Dicloran", "Cataflam"],
    drugClass: "NSAID",
    category: "Acetic acid derivative",
    strengths: ["25mg", "50mg", "75mg", "100mg SR"],
    defaultStrength: "50mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Peptic ulcer", "Renal impairment", "Heart failure", "NSAID allergy"],
    interactions: ["Warfarin", "Lithium", "ACE inhibitors", "Methotrexate"],
    sideEffects: ["GI upset", "Hepatotoxicity", "Cardiovascular risk", "Renal dysfunction"],
    notes: "Moderate-severe dental pain and inflammation. SR (slow release) formulation for BD dosing convenience. Liver function monitoring for prolonged use.",
    tags: ["inflammation", "pain", "SR", "moderate pain"],
  },
  {
    id: "ketorolac",
    genericName: "Ketorolac",
    brandNames: ["Toradol", "Ketanov", "Ketolac", "Ketorol"],
    drugClass: "NSAID",
    category: "Pyrrolizine carboxylic acid",
    strengths: ["10mg"],
    defaultStrength: "10mg",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Peptic ulcer", "Renal impairment", "Bleeding disorders", "NSAID allergy"],
    interactions: ["Anticoagulants", "Other NSAIDs", "ACE inhibitors"],
    sideEffects: ["GI bleeding", "Renal dysfunction", "Fluid retention"],
    notes: "Potent short-term NSAID for severe post-operative dental pain. Maximum 5 days oral use. Not for chronic use.",
    tags: ["severe pain", "post-op", "potent NSAID", "short-term"],
  },
  {
    id: "naproxen",
    genericName: "Naproxen",
    brandNames: ["Naprosyn", "Aleve", "Naprelan", "Napro"],
    drugClass: "NSAID",
    category: "Propionic acid derivative",
    strengths: ["250mg", "500mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Peptic ulcer", "Severe renal/hepatic disease", "Third trimester pregnancy"],
    interactions: ["Warfarin", "Lithium", "ACE inhibitors", "Aspirin"],
    sideEffects: ["GI upset", "Headache", "Dizziness", "Oedema"],
    notes: "Longer half-life allows BD dosing. Good for sustained pain control post-extraction or implant surgery.",
    tags: ["long-acting", "post-op", "inflammation", "BD dosing"],
  },
  {
    id: "etoricoxib",
    genericName: "Etoricoxib",
    brandNames: ["Arcoxia", "Tauxib", "Etoshine", "Nucoxia"],
    drugClass: "NSAID",
    category: "COX-2 selective inhibitor",
    strengths: ["60mg", "90mg", "120mg"],
    defaultStrength: "90mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Cardiovascular disease", "Uncontrolled hypertension", "Peptic ulcer (relative)"],
    interactions: ["Warfarin", "ACE inhibitors", "Lithium"],
    sideEffects: ["Oedema", "Hypertension", "GI upset (less than non-selective NSAIDs)"],
    notes: "COX-2 selective — lower GI risk. Preferred for patients at GI risk. Acute dental pain: 120mg OD up to 3 days.",
    tags: ["COX-2", "GI safe", "once daily", "post-op"],
  },

  // ─── CORTICOSTEROIDS ──────────────────────────────────────────────────────

  {
    id: "dexamethasone",
    genericName: "Dexamethasone",
    brandNames: ["Decadron", "Dexona", "Hexadrol", "Ozurdex"],
    drugClass: "Corticosteroid",
    category: "Systemic corticosteroid",
    strengths: ["0.5mg", "4mg", "8mg"],
    defaultStrength: "4mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "3 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Active infection (untreated)", "Peptic ulcer", "Diabetes (relative)", "Immunosuppression"],
    interactions: ["NSAIDs (GI bleeding)", "Diabetes drugs", "Antifungals"],
    sideEffects: ["Hyperglycaemia", "Immunosuppression", "Adrenal suppression (prolonged use)", "GI upset"],
    notes: "Used peri-operatively to reduce post-surgical oedema, trismus, and pain after wisdom tooth removal or extensive oral surgery. Short courses only.",
    tags: ["oedema", "post-op swelling", "wisdom tooth", "trismus", "anti-inflammatory"],
  },
  {
    id: "prednisolone",
    genericName: "Prednisolone",
    brandNames: ["Wysolone", "Omnacortil", "Deltacortril", "Prelone"],
    drugClass: "Corticosteroid",
    category: "Systemic corticosteroid",
    strengths: ["2.5mg", "5mg", "10mg", "20mg", "40mg"],
    defaultStrength: "10mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Active infection", "Live vaccines", "Peptic ulcer (relative)"],
    interactions: ["NSAIDs", "Antidiabetics", "Antifungals", "Antihypertensives"],
    sideEffects: ["Hyperglycaemia", "Osteoporosis (chronic)", "Weight gain", "Cushing's (chronic)"],
    notes: "Used for oral lichen planus, pemphigus, severe aphthous ulcers, and Bell's palsy. Taper when used >10 days.",
    tags: ["lichen planus", "pemphigus", "aphthous ulcer", "oral lesions"],
  },
  {
    id: "triamcinolone-topical",
    genericName: "Triamcinolone Acetonide",
    brandNames: ["Kenalog", "Kenacort-A", "Ledercort"],
    drugClass: "Corticosteroid",
    category: "Topical corticosteroid",
    strengths: ["0.1% paste"],
    defaultStrength: "0.1% paste",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "7 days",
    defaultDose: "Apply thin film",
    route: "Topical",
    foodInstruction: "Apply after meals and at bedtime",
    contraindications: ["Oral fungal infection", "Viral lesions", "Tuberculosis"],
    interactions: [],
    sideEffects: ["Secondary candidiasis (prolonged use)", "Mucosal atrophy"],
    notes: "Orabase paste for aphthous ulcers and oral lichen planus. Apply after meals and at bedtime. Thin film over ulcer.",
    tags: ["aphthous ulcer", "canker sore", "lichen planus", "topical", "oral paste"],
  },

  // ─── ANTIFUNGALS ──────────────────────────────────────────────────────────

  {
    id: "fluconazole",
    genericName: "Fluconazole",
    brandNames: ["Diflucan", "Forcan", "Syscan", "Fluka"],
    drugClass: "Antifungal",
    category: "Triazole antifungal",
    strengths: ["50mg", "100mg", "150mg", "200mg"],
    defaultStrength: "150mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "7 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "With or without food",
    contraindications: ["Hepatic failure", "QT prolongation", "Drug interactions (many)"],
    interactions: ["Warfarin", "Statins", "Benzodiazepines", "Phenytoin", "Cyclosporin"],
    sideEffects: ["Nausea", "Headache", "Hepatotoxicity (rare)", "QT prolongation"],
    notes: "For oral candidiasis (thrush), denture stomatitis, angular cheilitis. Oropharyngeal candidiasis: 200mg day 1 then 100mg OD. Check drug interactions carefully.",
    tags: ["candidiasis", "thrush", "oral candida", "denture stomatitis", "angular cheilitis"],
  },
  {
    id: "clotrimazole",
    genericName: "Clotrimazole",
    brandNames: ["Canesten", "Candid", "Clotrimazole"],
    drugClass: "Antifungal",
    category: "Imidazole antifungal",
    strengths: ["1% gel", "10mg lozenges"],
    defaultStrength: "1% gel",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "14 days",
    defaultDose: "Apply small amount",
    route: "Topical",
    foodInstruction: "After meals and at bedtime",
    contraindications: ["Hypersensitivity to imidazoles"],
    interactions: [],
    sideEffects: ["Local irritation", "Burning sensation"],
    notes: "Topical antifungal for oral candidiasis. Dissolve lozenge slowly in mouth. Continue treatment for 48h after symptoms resolve.",
    tags: ["candidiasis", "thrush", "topical antifungal", "oral gel"],
  },
  {
    id: "nystatin",
    genericName: "Nystatin",
    brandNames: ["Mycostatin", "Nystop", "Nilstat"],
    drugClass: "Antifungal",
    category: "Polyene antifungal",
    strengths: ["100,000 units/mL suspension", "500,000 units tablet"],
    defaultStrength: "100,000 units/mL",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "14 days",
    defaultDose: "4-6 mL (swish and swallow)",
    route: "Topical",
    foodInstruction: "After meals",
    contraindications: ["Hypersensitivity"],
    interactions: [],
    sideEffects: ["Nausea (if swallowed)", "Oral irritation"],
    notes: "First-line for mild oropharyngeal candidiasis. Swish in mouth for 2 minutes then swallow. Continue 48h after resolution. Not absorbed systemically.",
    tags: ["candidiasis", "thrush", "oral suspension", "swish and swallow"],
  },

  // ─── ANTIHISTAMINES ───────────────────────────────────────────────────────

  {
    id: "cetirizine",
    genericName: "Cetirizine",
    brandNames: ["Zyrtec", "Alerid", "Cetzine", "CTZ"],
    drugClass: "Antihistamine",
    category: "Second-generation antihistamine",
    strengths: ["5mg", "10mg"],
    defaultStrength: "10mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "At bedtime",
    contraindications: ["Severe renal impairment"],
    interactions: ["CNS depressants (mild)", "Alcohol"],
    sideEffects: ["Drowsiness (minimal)", "Dry mouth", "Headache"],
    notes: "For allergic reactions to dental materials, post-surgical swelling management, or allergic angioedema. Minimal sedation vs first-generation.",
    tags: ["allergy", "allergic reaction", "swelling", "urticaria"],
  },
  {
    id: "chlorpheniramine",
    genericName: "Chlorpheniramine Maleate",
    brandNames: ["Piriton", "Chlor-Trimeton", "CTM", "Teldane"],
    drugClass: "Antihistamine",
    category: "First-generation antihistamine",
    strengths: ["2mg", "4mg"],
    defaultStrength: "4mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Glaucoma", "Urinary retention", "MAO inhibitors"],
    interactions: ["CNS depressants", "MAOIs", "Alcohol"],
    sideEffects: ["Sedation", "Dry mouth", "Urinary retention", "Constipation"],
    notes: "Sedating — use at night or when rest is desired. For acute allergic reactions, urticaria. Warn about driving impairment.",
    tags: ["allergy", "sedating antihistamine", "allergic reaction"],
  },

  // ─── ANXIOLYTICS ──────────────────────────────────────────────────────────

  {
    id: "diazepam",
    genericName: "Diazepam",
    brandNames: ["Valium", "Calmpose", "Diastat", "Antenex"],
    drugClass: "Anxiolytic",
    category: "Benzodiazepine",
    strengths: ["2mg", "5mg", "10mg"],
    defaultStrength: "5mg",
    defaultFrequency: "As needed (SOS)",
    defaultDuration: "1 day",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "1 hour before procedure",
    contraindications: ["Respiratory depression", "Myasthenia gravis", "Acute narrow-angle glaucoma", "Alcohol intoxication"],
    interactions: ["CNS depressants", "Alcohol", "Opioids (risk of apnoea)", "Antifungals"],
    sideEffects: ["Sedation", "Respiratory depression", "Dependence", "Paradoxical excitement"],
    notes: "Pre-operative anxiolysis for highly anxious dental patients. Single night-before or morning-of dose. Schedule H drug. Requires informed consent. Patient must not drive.",
    tags: ["dental anxiety", "anxiolysis", "pre-operative", "benzodiazepine", "sedation"],
  },
  {
    id: "midazolam",
    genericName: "Midazolam",
    brandNames: ["Dormicum", "Versed", "Hypnovel"],
    drugClass: "Anxiolytic",
    category: "Benzodiazepine",
    strengths: ["7.5mg"],
    defaultStrength: "7.5mg",
    defaultFrequency: "Stat (single dose)",
    defaultDuration: "1 day",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "30-60 minutes before procedure",
    contraindications: ["Respiratory depression", "Pregnancy", "Severe hepatic disease"],
    interactions: ["CNS depressants", "Opioids", "Azole antifungals", "Macrolide antibiotics"],
    sideEffects: ["Sedation", "Amnesia", "Respiratory depression", "Disinhibition"],
    notes: "Short-acting. Produces anterograde amnesia. Ideal for IV conscious sedation (IV formulation) or pre-procedure oral anxiolysis. Requires resuscitation equipment available.",
    tags: ["conscious sedation", "dental anxiety", "amnesia", "pre-procedure"],
  },

  // ─── MOUTHWASH & TOPICAL ──────────────────────────────────────────────────

  {
    id: "chlorhexidine",
    genericName: "Chlorhexidine Gluconate",
    brandNames: ["Corsodyl", "Hexidine", "Chlorhex", "Peridex", "Periogard"],
    drugClass: "Mouthwash & Topical",
    category: "Antiseptic mouthwash",
    strengths: ["0.12% mouthwash", "0.2% mouthwash", "1% gel"],
    defaultStrength: "0.2% mouthwash",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "14 days",
    defaultDose: "10-15 mL (rinse 30 sec)",
    route: "Topical",
    foodInstruction: "After meals — do not swallow",
    contraindications: ["Hypersensitivity", "Use with toothpaste (incompatible — wait 30 min)"],
    interactions: ["Incompatible with anionic compounds in toothpaste"],
    sideEffects: ["Tooth staining (brown)", "Altered taste", "Mucosal desquamation", "Parotid gland swelling"],
    notes: "Gold standard antiseptic for post-operative care, periodontal treatment, and plaque control. Staining is dose/time dependent. Use for limited periods.",
    tags: ["mouthwash", "periodontal", "post-op", "antiseptic", "plaque control"],
  },
  {
    id: "povidone-iodine",
    genericName: "Povidone-Iodine",
    brandNames: ["Betadine", "Wokadine", "Isodine"],
    drugClass: "Mouthwash & Topical",
    category: "Antiseptic",
    strengths: ["0.5%", "1% mouthwash/gargle", "5% solution"],
    defaultStrength: "1% mouthwash",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "7 days",
    defaultDose: "10 mL (dilute 1:1 with water, rinse 30 sec)",
    route: "Topical",
    foodInstruction: "Do not swallow",
    contraindications: ["Iodine hypersensitivity", "Thyroid disorders (systemic absorption possible)", "Pregnancy"],
    interactions: ["Lithium", "Thyroid medications"],
    sideEffects: ["Mucosal staining", "Thyroid dysfunction (systemic absorption)"],
    notes: "Broad-spectrum antiseptic. Dilute before use as mouthwash. Also used for socket irrigation post-extraction.",
    tags: ["antiseptic", "mouthwash", "wound care", "socket irrigation"],
  },
  {
    id: "lidocaine-gel",
    genericName: "Lidocaine Gel",
    brandNames: ["Xylocaine Gel", "Lignocaine Gel", "Xylox"],
    drugClass: "Local Anesthetic",
    category: "Topical local anaesthetic",
    strengths: ["2% gel", "5% ointment"],
    defaultStrength: "2% gel",
    defaultFrequency: "As needed (SOS)",
    defaultDuration: "As required",
    defaultDose: "Apply small amount",
    route: "Topical",
    foodInstruction: "Before meals to reduce pain during eating",
    contraindications: ["Hypersensitivity to amide local anaesthetics"],
    interactions: ["Antiarrhythmics"],
    sideEffects: ["Transient numbness", "Rare systemic absorption if overused"],
    notes: "Surface anaesthetic for ulcer pain, before injection, or needle phobia. Onset in 2-3 minutes. Duration 15-30 min.",
    tags: ["topical anaesthetic", "ulcer pain", "surface anaesthetic", "needle phobia"],
  },
  {
    id: "benzydamine",
    genericName: "Benzydamine HCl",
    brandNames: ["Tantum Verde", "Difflam", "Benzoflex"],
    drugClass: "Mouthwash & Topical",
    category: "Topical NSAID/Anaesthetic",
    strengths: ["0.15% mouthwash", "0.15% spray"],
    defaultStrength: "0.15% mouthwash",
    defaultFrequency: "Every 4-6 hours (PRN)",
    defaultDuration: "7 days",
    defaultDose: "15 mL (rinse 30 sec, spit out)",
    route: "Topical",
    foodInstruction: "Do not swallow",
    contraindications: ["Hypersensitivity"],
    interactions: [],
    sideEffects: ["Stinging/burning (dilute if occurs)", "Numbness"],
    notes: "Anti-inflammatory analgesic mouthwash for post-extraction pain, mucositis, pharyngitis, ANUG. Can be diluted 1:1 with water if stinging occurs.",
    tags: ["mouthwash", "mucositis", "post-extraction", "anti-inflammatory", "analgesic rinse"],
  },

  // ─── ANTACID / PPI ────────────────────────────────────────────────────────

  {
    id: "omeprazole",
    genericName: "Omeprazole",
    brandNames: ["Prilosec", "Losec", "Omez", "Ocid"],
    drugClass: "Proton Pump Inhibitor",
    category: "PPI",
    strengths: ["10mg", "20mg", "40mg"],
    defaultStrength: "20mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "14 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "Before breakfast (30 min before meals)",
    contraindications: ["Hypersensitivity"],
    interactions: ["Clopidogrel", "Methotrexate", "Warfarin", "Ketoconazole"],
    sideEffects: ["Headache", "Diarrhoea", "Nausea", "Hypomagnesaemia (long-term)"],
    notes: "GI protection when prescribing NSAIDs for >3 days. Also for GERD and acid reflux.",
    tags: ["gastric protection", "NSAID cover", "PPI", "acid reflux", "GERD"],
  },
  {
    id: "pantoprazole",
    genericName: "Pantoprazole",
    brandNames: ["Pantoloc", "Pan", "Protium", "Pantozol"],
    drugClass: "Proton Pump Inhibitor",
    category: "PPI",
    strengths: ["20mg", "40mg"],
    defaultStrength: "40mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "14 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "Before breakfast",
    contraindications: ["Hypersensitivity"],
    interactions: ["Methotrexate", "Clopidogrel (less than Omeprazole)"],
    sideEffects: ["Headache", "Diarrhoea", "Nausea"],
    notes: "Preferred PPI with fewer drug interactions than Omeprazole. Good choice when patient is also on Clopidogrel.",
    tags: ["gastric protection", "PPI", "fewer interactions", "acid reduction"],
  },

  // ─── ANTIEMETICS ──────────────────────────────────────────────────────────

  {
    id: "ondansetron",
    genericName: "Ondansetron",
    brandNames: ["Zofran", "Emeset", "Ondem", "Ondanset"],
    drugClass: "Antiemetic",
    category: "5-HT3 antagonist",
    strengths: ["4mg", "8mg"],
    defaultStrength: "4mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "3 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "With or without food",
    contraindications: ["QT prolongation", "Congenital long QT syndrome"],
    interactions: ["QT-prolonging drugs", "Tramadol", "SSRIs (serotonin syndrome)"],
    sideEffects: ["Constipation", "Headache", "QT prolongation (high doses)"],
    notes: "For post-operative nausea after dental procedures under GA/sedation, or nausea from antibiotics/opioids.",
    tags: ["nausea", "vomiting", "post-op", "anti-nausea"],
  },
  {
    id: "metoclopramide",
    genericName: "Metoclopramide",
    brandNames: ["Reglan", "Perinorm", "Emitil", "Maxolon"],
    drugClass: "Antiemetic",
    category: "Dopamine antagonist",
    strengths: ["5mg", "10mg"],
    defaultStrength: "10mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "3 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "Before meals",
    contraindications: ["GI haemorrhage/obstruction", "Parkinson's disease", "Phaeochromocytoma"],
    interactions: ["Dopamine agonists", "Antipsychotics", "Opioids"],
    sideEffects: ["Drowsiness", "Extrapyramidal effects", "Tardive dyskinesia (long-term)"],
    notes: "For drug-induced nausea (antibiotics, opioids). Short-term use only — extrapyramidal risk with prolonged use.",
    tags: ["nausea", "anti-nausea", "GI motility"],
  },

  // ─── VITAMINS & SUPPLEMENTS ───────────────────────────────────────────────

  {
    id: "vitamin-c",
    genericName: "Ascorbic Acid (Vitamin C)",
    brandNames: ["Limcee", "Celin", "Ester-C", "Ascorval"],
    drugClass: "Vitamin & Supplement",
    category: "Water-soluble vitamin",
    strengths: ["250mg", "500mg", "1000mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "30 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Renal stones (high doses)", "Haemochromatosis"],
    interactions: ["Iron supplements (enhances absorption)"],
    sideEffects: ["GI upset (high doses)", "Renal stones (high doses)"],
    notes: "Collagen synthesis essential for wound healing post-surgery and gingival health. Adjunct in periodontal disease management. Scurvy treatment.",
    tags: ["wound healing", "periodontal", "gingival health", "collagen", "post-op healing"],
  },
  {
    id: "calcium-vitamin-d",
    genericName: "Calcium Carbonate + Vitamin D3",
    brandNames: ["Shelcal", "Calcimax", "Calcirol", "Calcium Sandoz"],
    drugClass: "Vitamin & Supplement",
    category: "Calcium/Vitamin D supplement",
    strengths: ["500mg/250IU", "1000mg/400IU"],
    defaultStrength: "500mg/250IU",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "90 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals (improves absorption)",
    contraindications: ["Hypercalcaemia", "Hypercalciuria", "Severe renal impairment"],
    interactions: ["Tetracyclines", "Fluoroquinolones", "Bisphosphonates", "Iron (separate by 2h)", "Thiazide diuretics"],
    sideEffects: ["Constipation", "Nausea", "Hypercalcaemia (high doses)"],
    notes: "Post-implant surgery bone healing, osteoporosis management, periodontal bone health. Take separately from fluoride-containing preparations.",
    tags: ["bone health", "implant", "osteoporosis", "post-implant", "calcium"],
  },
  {
    id: "vitamin-b12",
    genericName: "Methylcobalamin (Vitamin B12)",
    brandNames: ["Mecobalamin", "Methycobal", "Cobadex", "Neurobion"],
    drugClass: "Vitamin & Supplement",
    category: "B-vitamin",
    strengths: ["500mcg", "1500mcg"],
    defaultStrength: "500mcg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "30 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Hypersensitivity"],
    interactions: [],
    sideEffects: ["Rare: diarrhoea, rash"],
    notes: "For glossitis, burning mouth syndrome, recurrent aphthous ulcers, and peripheral neuropathy (post-nerve block). Active form preferred over cyanocobalamin.",
    tags: ["burning mouth", "glossitis", "aphthous ulcer", "neuropathy", "nerve damage"],
  },
  {
    id: "folic-acid",
    genericName: "Folic Acid",
    brandNames: ["Folvite", "Folsafe", "Fefol", "Folic-500"],
    drugClass: "Vitamin & Supplement",
    category: "B-vitamin",
    strengths: ["400mcg", "1mg", "5mg"],
    defaultStrength: "5mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "30 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Undiagnosed megaloblastic anaemia"],
    interactions: ["Methotrexate (antagonist)", "Phenytoin", "Sulfasalazine"],
    sideEffects: ["Rare: GI upset"],
    notes: "For aphthous ulcers, glossitis, and patients on Methotrexate. Tissue healing support. Adjunct in oral mucositis treatment.",
    tags: ["aphthous ulcer", "glossitis", "mucositis", "healing", "megaloblastic"],
  },
  {
    id: "zinc-supplement",
    genericName: "Zinc Sulphate",
    brandNames: ["Zincovit", "Zinconia", "Zinconia Plus"],
    drugClass: "Vitamin & Supplement",
    category: "Trace mineral",
    strengths: ["20mg", "45mg"],
    defaultStrength: "45mg",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "30 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: [],
    interactions: ["Fluoroquinolones", "Tetracyclines", "Iron (separate by 2h)"],
    sideEffects: ["GI upset", "Nausea", "Metallic taste"],
    notes: "For wound healing post-surgery, recurrent aphthous ulcers, taste disorders, burning mouth syndrome. Deficiency is associated with poor periodontal healing.",
    tags: ["wound healing", "aphthous", "taste disorder", "healing"],
  },

  // ─── FLUORIDE ─────────────────────────────────────────────────────────────

  {
    id: "sodium-fluoride",
    genericName: "Sodium Fluoride",
    brandNames: ["Fluor-A-Day", "Prevident", "Dentimax F"],
    drugClass: "Fluoride",
    category: "Fluoride supplement",
    strengths: ["0.05% rinse", "0.25mg tablet"],
    defaultStrength: "0.05% rinse",
    defaultFrequency: "Once daily (OD)",
    defaultDuration: "Ongoing",
    defaultDose: "10 mL (rinse 1 min, spit)",
    route: "Topical",
    foodInstruction: "Before bed — do not eat/drink 30 min after",
    contraindications: ["Fluoride water >0.6 ppm (tablets)", "Age < 6 years (rinse)"],
    interactions: [],
    sideEffects: ["Fluorosis (excessive ingestion)", "GI upset (if swallowed)"],
    notes: "High-risk caries patients — daily fluoride rinse or prescription-strength toothpaste. In-office application of 5% NaF varnish every 3-6 months.",
    tags: ["caries prevention", "remineralisation", "fluoride", "decay prevention"],
  },

  // ─── HAEMOSTATICS ─────────────────────────────────────────────────────────

  {
    id: "tranexamic-acid",
    genericName: "Tranexamic Acid",
    brandNames: ["Cyklokapron", "Traxyl", "Pause MF", "Exacyl"],
    drugClass: "Haemostatic",
    category: "Antifibrinolytic",
    strengths: ["250mg", "500mg"],
    defaultStrength: "500mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["History of thromboembolic disease", "Colour vision defects (long-term)", "Renal impairment (dose adjustment)"],
    interactions: ["Hormonal contraceptives (thrombosis risk)", "Factor IX complexes"],
    sideEffects: ["Nausea", "Diarrhoea", "Thrombosis risk", "Visual disturbances (prolonged)"],
    notes: "For post-extraction haemorrhage, especially in anticoagulated patients. Can also be used as a 4.8% mouthwash (swish and spit) without systemic absorption. Discuss with physician in anticoagulated patients.",
    tags: ["bleeding", "post-extraction", "anticoagulated patient", "haemostasis", "prolonged bleeding"],
  },

  // ─── ANTIVIRALS ───────────────────────────────────────────────────────────

  {
    id: "acyclovir",
    genericName: "Acyclovir",
    brandNames: ["Zovirax", "Acivir", "Herpex", "Cyclovax"],
    drugClass: "Antiviral",
    category: "Nucleoside analogue",
    strengths: ["200mg", "400mg", "800mg", "5% cream"],
    defaultStrength: "400mg",
    defaultFrequency: "Four times daily (QID)",
    defaultDuration: "7 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "With or without food — maintain adequate hydration",
    contraindications: ["Renal impairment (dose adjust)", "Hypersensitivity"],
    interactions: ["Nephrotoxic drugs", "Zidovudine"],
    sideEffects: ["Nausea", "Headache", "Renal dysfunction", "Neurological (high doses)"],
    notes: "For primary herpetic gingivostomatitis, herpes labialis, and herpes zoster. Early treatment critical — start within 72h. Maintain good hydration. Topical cream for recurrent labial herpes.",
    tags: ["herpes", "cold sore", "herpetic stomatitis", "HSV", "herpes labialis", "herpes zoster"],
  },
  {
    id: "valacyclovir",
    genericName: "Valacyclovir",
    brandNames: ["Valtrex", "Valcivir", "Zelitrex"],
    drugClass: "Antiviral",
    category: "Prodrug — Nucleoside analogue",
    strengths: ["500mg", "1000mg"],
    defaultStrength: "1000mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "7 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "With or without food",
    contraindications: ["Renal impairment (dose adjust)", "Hypersensitivity to valacyclovir/acyclovir"],
    interactions: ["Nephrotoxic drugs", "Cimetidine", "Probenecid"],
    sideEffects: ["Headache", "Nausea", "Renal dysfunction (high doses in immunocompromised)"],
    notes: "Prodrug of acyclovir with better bioavailability — BD dosing vs 5x/day for Acyclovir. For herpes zoster: 1g TDS × 7 days. Cold sore suppression: 500mg OD.",
    tags: ["herpes zoster", "shingles", "cold sore", "HSV", "better bioavailability"],
  },

  // ─── MUSCLE RELAXANTS ─────────────────────────────────────────────────────

  {
    id: "diclofenac-muscle",
    genericName: "Diclofenac + Thiocolchicoside",
    brandNames: ["Signoflam", "Diclowin Plus", "Ikolchi"],
    drugClass: "Muscle Relaxant",
    category: "NSAID + Muscle relaxant combination",
    strengths: ["50mg + 4mg"],
    defaultStrength: "50mg + 4mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "5 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Peptic ulcer", "Muscle dystrophies", "Renal impairment"],
    interactions: ["CNS depressants", "Anticoagulants"],
    sideEffects: ["GI upset", "Drowsiness", "Diarrhoea"],
    notes: "For TMJ pain, trismus, post-surgical muscle spasm. The muscle relaxant component helps with jaw mobility post-extensive dental work.",
    tags: ["TMJ", "trismus", "muscle spasm", "jaw pain", "muscle relaxant"],
  },
  {
    id: "baclofen",
    genericName: "Baclofen",
    brandNames: ["Lioresal", "Baclof", "Baclopar"],
    drugClass: "Muscle Relaxant",
    category: "GABA-B agonist",
    strengths: ["5mg", "10mg", "25mg"],
    defaultStrength: "10mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "7 days",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Stroke", "Abrupt withdrawal (risk of seizures)", "Renal impairment"],
    interactions: ["CNS depressants", "Antihypertensives", "Tricyclic antidepressants"],
    sideEffects: ["Drowsiness", "Muscle weakness", "Dizziness", "Nausea"],
    notes: "For severe TMJ disorder, bruxism-related muscle pain, and trigeminal neuralgia adjunct. Do not stop abruptly.",
    tags: ["TMJ", "bruxism", "trigeminal neuralgia", "muscle spasm"],
  },
  {
    id: "carbamazepine",
    genericName: "Carbamazepine",
    brandNames: ["Tegretol", "Mazetol", "Zen Retard", "Carbatrol"],
    drugClass: "Analgesic",
    category: "Anticonvulsant / Neuropathic pain",
    strengths: ["100mg", "200mg", "400mg CR"],
    defaultStrength: "200mg",
    defaultFrequency: "Twice daily (BD)",
    defaultDuration: "As directed",
    defaultDose: "1 tablet",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["AV block", "Bone marrow suppression", "MAOIs", "Porphyria"],
    interactions: ["Phenytoin", "Oral contraceptives", "Warfarin", "Many CYP3A4 drugs"],
    sideEffects: ["Dizziness", "Diplopia", "Hyponatraemia", "Blood dyscrasias", "Stevens-Johnson (rare)"],
    notes: "First-line for trigeminal neuralgia. Start low (100mg BD), titrate to effect. Monitor CBC and LFTs. Significant drug interactions.",
    tags: ["trigeminal neuralgia", "neuropathic pain", "facial pain", "anticonvulsant"],
  },
  {
    id: "gabapentin",
    genericName: "Gabapentin",
    brandNames: ["Neurontin", "Gabantin", "Gaba", "Gabapax"],
    drugClass: "Analgesic",
    category: "Anticonvulsant / Neuropathic pain",
    strengths: ["100mg", "300mg", "400mg"],
    defaultStrength: "300mg",
    defaultFrequency: "Three times daily (TDS)",
    defaultDuration: "30 days",
    defaultDose: "1 capsule",
    route: "Oral",
    foodInstruction: "After meals",
    contraindications: ["Renal impairment (dose adjust)"],
    interactions: ["CNS depressants", "Antacids (reduce absorption)", "Morphine"],
    sideEffects: ["Dizziness", "Somnolence", "Peripheral oedema", "Weight gain"],
    notes: "For chronic orofacial pain, post-herpetic neuralgia, burning mouth syndrome, and neuropathic pain after dental trauma. Start low and titrate.",
    tags: ["neuropathic pain", "orofacial pain", "burning mouth", "post-herpetic", "chronic pain"],
  },
]

// ─── Search and utility functions ─────────────────────────────────────────────

export function searchMedicines(query: string): Medicine[] {
  if (!query || query.trim().length < 2) return []
  const q = query.toLowerCase().trim()
  return MEDICINES.filter(m =>
    m.genericName.toLowerCase().includes(q) ||
    m.brandNames.some(b => b.toLowerCase().includes(q)) ||
    m.drugClass.toLowerCase().includes(q) ||
    m.category.toLowerCase().includes(q) ||
    m.tags.some(t => t.toLowerCase().includes(q))
  ).slice(0, 10)
}

export function getMedicineById(id: string): Medicine | undefined {
  return MEDICINES.find(m => m.id === id)
}

export function getMedicinesByClass(drugClass: DrugClass): Medicine[] {
  return MEDICINES.filter(m => m.drugClass === drugClass)
}

export function checkInteractions(selectedIds: string[]): Array<{ drug1: string; drug2: string; description: string }> {
  const alerts: Array<{ drug1: string; drug2: string; description: string }> = []
  const selected = selectedIds.map(id => getMedicineById(id)).filter(Boolean) as Medicine[]

  for (let i = 0; i < selected.length; i++) {
    for (let j = i + 1; j < selected.length; j++) {
      const a = selected[i]
      const b = selected[j]
      const aInteractsWithB = a.interactions.some(inter =>
        b.genericName.toLowerCase().includes(inter.toLowerCase()) ||
        inter.toLowerCase().includes(b.genericName.toLowerCase())
      )
      const bInteractsWithA = b.interactions.some(inter =>
        a.genericName.toLowerCase().includes(inter.toLowerCase()) ||
        inter.toLowerCase().includes(a.genericName.toLowerCase())
      )
      if (aInteractsWithB || bInteractsWithA) {
        alerts.push({
          drug1: a.genericName,
          drug2: b.genericName,
          description: `Potential interaction between ${a.genericName} and ${b.genericName}`,
        })
      }
    }
  }
  return alerts
}

export const ALL_DRUG_CLASSES: DrugClass[] = [
  "Antibiotic", "Analgesic", "NSAID", "Antifungal", "Antiseptic",
  "Corticosteroid", "Antihistamine", "Anxiolytic", "Antacid",
  "Proton Pump Inhibitor", "Antiemetic", "Vitamin & Supplement",
  "Mouthwash & Topical", "Local Anesthetic", "Muscle Relaxant",
  "Antiviral", "Decongestant", "Fluoride", "Haemostatic",
  "Bone Resorption Inhibitor",
]

export const FREQUENCY_OPTIONS: Frequency[] = [
  "Once daily (OD)", "Twice daily (BD)", "Three times daily (TDS)",
  "Four times daily (QID)", "Every 6 hours (Q6H)", "Every 8 hours (Q8H)",
  "Every 12 hours (Q12H)", "Every 4-6 hours (PRN)", "At bedtime (HS)",
  "As needed (SOS)", "Once weekly", "Stat (single dose)",
]

export const DURATION_OPTIONS = [
  "1 day", "2 days", "3 days", "5 days", "7 days", "10 days",
  "14 days", "21 days", "30 days", "60 days", "90 days",
  "As directed", "Ongoing",
]

export const DOSE_OPTIONS = [
  "1 tablet", "2 tablets", "½ tablet", "1 capsule", "2 capsules",
  "5 mL", "10 mL", "15 mL", "Apply thin film", "Apply small amount",
  "1 lozenge", "As directed",
]

export default MEDICINES
